region              = "us-east-1"
bucket_name         = "ping-cloud-logs-poc"
lambda_name         = "ping-cloud-hola-mundo"
lambda_role_name    = "ping-cloud-lambda-role"
scheduler_role_name = "ping-cloud-eventbridge-role"